#!/bin/bash
# Full-text search query processor.
set -e
basedir="$(dirname "$0")"
joins="$basedir/joins.py"
msgs="$basedir/msgs.py"
look="$basedir/skiplook.py"
: ${1?usage: $0 mbox keywords}
mbox="$1"

case "$#" in
2) "$joins" <("$look" "$2" "$mbox".idx/* ) | "$msgs" "$mbox" ;;
3) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
4) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
5) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
            <("$look" "$5" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
6) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
            <("$look" "$5" "$mbox".idx/* ) \
            <("$look" "$6" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
esac
