#!/bin/bash
set -e
devel=/home/kragen/devel
joins="$devel/joins.py"
msgs="$devel/msgs.py"
look="$devel/skiplook.py"
: ${1?usage: $0 mbox keywords}
mbox="$1"

case "$#" in
2) "$joins" <("$look" "$2" "$mbox".idx/* ) | "$msgs" "$mbox" ;;
3) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
4) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
5) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
            <("$look" "$5" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
6) "$joins" <("$look" "$2" "$mbox".idx/* ) \
            <("$look" "$3" "$mbox".idx/* ) \
            <("$look" "$4" "$mbox".idx/* ) \
            <("$look" "$5" "$mbox".idx/* ) \
            <("$look" "$6" "$mbox".idx/* ) \
    | "$msgs" "$mbox" ;;
esac
